name = "VerilogWriter"
uuid = "609488a3-1988-4612-be37-e0d5b22d8f97"
authors = ["t-f-marfil and contributors"]
version = "0.4.0"

[deps]
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
